--liquibase formatted sql
--changeset rafael:202504111424
--comment: boards table create

CREATE TABLE BOARDS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);


--rollback DROP TABLE BOARDS